[Normal]
G1 = "<Super>+1"
G2 = "<Super>+2"
G3 = "<Super>+3"
G4 = "<Super>+4"
G5 = "<Super>+5"
G6 = "<Super>+6"

[M1]
G1 = "<Super>+<Shift>+1"
G2 = "<Super>+<Shift>+2"
G3 = "<Super>+<Shift>+3"
G4 = "<Super>+<Shift>+4"
G5 = "<Super>+<Shift>+5"
G6 = "<Super>+<Shift>+6"

[M2]
G1 = "<Super>+<Shift>+1"
G2 = "<Super>+<Shift>+2"
G3 = "<Super>+<Shift>+3"
G4 = "<Super>+<Shift>+4"
G5 = "<Super>+<Shift>+5"
G6 = "<Super>+<Shift>+6"

#[M3]
#G1 = ""
#G2 = ""
#G3 = ""
#G4 = ""
#G5 = ""
#G6 = ""
